trigger:
  paths:
    include:
      - users/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'users'
  PROJECT_ID: '<your-gcp-project>'
  CLUSTER_NAME: 'gke-microservices'
  CLUSTER_ZONE: 'asia-south1-a'
  NAMESPACE: 'microservices-prod'

steps:
- task: GoogleCloudSDKInstaller@1

- script: |
    gcloud auth activate-service-account --key-file=$(GOOGLE_APPLICATION_CREDENTIALS)
    gcloud config set project $PROJECT_ID
    gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE
  displayName: 'Authenticate with GCP'

- script: |
    docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$(Build.BuildId) ./users
    docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- script: |
    sed -i "s|IMAGE_PLACEHOLDER|gcr.io/$PROJECT_ID/$IMAGE_NAME:$(Build.BuildId)|g" users/manifests/deployment.yaml
    kubectl apply -f users/manifests/ -n $NAMESPACE
  displayName: 'Deploy to GKE'
